version: '3'
services:
    postgresql:
        image: postgres:latest
        container_name: postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=password
        volumes:
            - ${PWD}/pgdata:/var/lib/postgresql/data
